# Generated by Django 6.0.4 on 2026-06-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("silver_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SilverBankInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_number", models.CharField(max_length=30)),
                ("full_name", models.CharField(max_length=255)),
                ("sheba", models.CharField(max_length=34)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
