# Generated by Django 6.0.4 on 2026-06-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_app', '0002_silverbankinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='silverproduct',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
