# Generated by Django 6.0.4 on 2026-05-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_app', '0005_silverproduct_physicaldeliveryorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicaldeliveryorder',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس ارسال'),
        ),
        migrations.AddField(
            model_name='physicaldeliveryorder',
            name='delivery_method',
            field=models.CharField(choices=[('COURIER', 'تحویل درب منزل'), ('IN_PERSON', 'تحویل حضوری در دفتر')], default='IN_PERSON', max_length=15),
        ),
        migrations.AddField(
            model_name='physicaldeliveryorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='physicaldeliveryorder',
            name='payment_method',
            field=models.CharField(choices=[('SILVER', 'پرداخت با نقره'), ('TOMAN', 'پرداخت مستقیم تومانی')], default='SILVER', max_length=10),
        ),
        migrations.AlterField(
            model_name='physicaldeliveryorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('PREPARING', 'در حال آماده\u200cسازی'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='physicaldeliveryorder',
            name='total_price_toman',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
