# Generated by Django 6.0.4 on 2026-07-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_app', '0005_alter_silverinventory_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='silverorder',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
