# Generated by Django 6.0.4 on 2026-05-25 00:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_app', '0006_physicaldeliveryorder_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SilverPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='physicaldeliveryorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='physicaldeliveryorder',
            name='user',
        ),
        migrations.RenameField(
            model_name='silverinventory',
            old_name='total_withdrawn_gr',
            new_name='blocked_balance',
        ),
        migrations.RenameField(
            model_name='silvertransaction',
            old_name='amount_toman',
            new_name='price_per_gram',
        ),
        migrations.RemoveField(
            model_name='silverinventory',
            name='total_spent_toman',
        ),
        migrations.RemoveField(
            model_name='silverproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='silverproduct',
            name='title',
        ),
        migrations.RemoveField(
            model_name='silverproduct',
            name='total_weight_with_packaging',
        ),
        migrations.RemoveField(
            model_name='silverproduct',
            name='weight_gr',
        ),
        migrations.AddField(
            model_name='silverinventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='silver/products/'),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='inventory_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='price',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='weight',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silvertransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silvertransaction',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='silvertransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silvertransaction',
            name='tracking_code',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silvertransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='silvertransaction',
            name='amount_gr',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='silvertransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'ناموفق')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='silvertransaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'خرید'), ('SELL', 'فروش')], max_length=20),
        ),
        migrations.CreateModel(
            name='SilverCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silver_app.silverproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SilverFinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('type', models.CharField(choices=[('DEPOSIT', 'واریز'), ('WITHDRAW', 'برداشت')], max_length=20)),
                ('method', models.CharField(choices=[('ONLINE', 'آنلاین'), ('CARD_TO_CARD', 'کارت به کارت'), ('BANK', 'بانکی'), ('GOLD', 'تبدیل به طلا')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('COMPLETED', 'تکمیل شده'), ('FAILED', 'ناموفق')], default='PENDING', max_length=20)),
                ('tracking_code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SilverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_silver_amount', models.DecimalField(decimal_places=5, max_digits=20)),
                ('total_toman_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('SHIPPED', 'ارسال شده'), ('COMPLETED', 'تکمیل شده'), ('CANCELLED', 'لغو شده')], default='PENDING', max_length=20)),
                ('tracking_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SilverOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_time', models.DecimalField(decimal_places=0, max_digits=20)),
                ('weight_at_time', models.DecimalField(decimal_places=5, max_digits=20)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='silver_app.silverorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='silver_app.silverproduct')),
            ],
        ),
        migrations.CreateModel(
            name='SilverPriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_price', models.DecimalField(decimal_places=5, max_digits=20)),
                ('alert_type', models.CharField(choices=[('ABOVE', 'بالاتر'), ('BELOW', 'پایین\u200cتر')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SilverReferralEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_referral_earnings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SilverWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('blocked_balance', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='silver_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BankCard',
        ),
        migrations.DeleteModel(
            name='PhysicalDeliveryOrder',
        ),
    ]
