# Generated by Django 6.0.4 on 2026-06-01 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_feesetting_gold_referral_percent_and_more'),
        ('silver_app', '0007_silverpricehistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SilverProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='silverpricealert',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='silverpricehistory',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='silverreferralearning',
            old_name='referred_user',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='silverproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='silverreferralearning',
            name='referrer',
        ),
        migrations.AddField(
            model_name='silverfinancialtransaction',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silverfinancialtransaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silverfinancialtransaction',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='silver_receipts/'),
        ),
        migrations.AddField(
            model_name='silverfinancialtransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='silverfinancialtransaction',
            name='user_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankcard'),
        ),
        migrations.AddField(
            model_name='silverorder',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silverorder',
            name='city',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silverorder',
            name='delivery_type',
            field=models.CharField(choices=[('HOME', 'ارسال'), ('IN_PERSON', 'حضوری')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silverorder',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silverorder',
            name='payment_method',
            field=models.CharField(choices=[('SILVER', 'نقره'), ('TOMAN', 'کیف پول')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silverorder',
            name='plaque',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='silverorder',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='silverorder',
            name='province',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='silverorder',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='silverorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='buy_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='delivery_type',
            field=models.CharField(choices=[('HOME', 'ارسال به منزل'), ('IN_PERSON', 'تحویل حضوری')], default='HOME', max_length=20),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='total_weight_with_fees',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='silverreferralearning',
            name='source_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='silverfinancialtransaction',
            name='method',
            field=models.CharField(choices=[('ONLINE', 'آنلاین'), ('CARD_TO_CARD', 'کارت به کارت'), ('BANK', 'بانکی')], max_length=30),
        ),
        migrations.AlterField(
            model_name='silverpricehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='silverproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='silver_products/'),
        ),
        migrations.AddField(
            model_name='silverproduct',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='silver_app.silverproductcategory'),
        ),
        migrations.CreateModel(
            name='SilverRecentDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_type', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SilverRecentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('status', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('plaque', models.CharField(blank=True, max_length=20, null=True)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='silver_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='SilverCart',
        ),
        migrations.DeleteModel(
            name='SilverPriceAlert',
        ),
    ]
