# Generated by Django 6.0.4 on 2026-07-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("silver_app", "0010_rename_balance_silverwallet_accessible_toman_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="silverorder",
            options={
                "verbose_name": "سفارش نقره",
                "verbose_name_plural": "سفارشات نقره",
            },
        ),
        migrations.AlterModelOptions(
            name="silverorderitem",
            options={
                "verbose_name": "آیتم سفارش نقره",
                "verbose_name_plural": "آیتم\u200cهای سفارش نقره",
            },
        ),
        migrations.AlterModelOptions(
            name="silverorderstatushistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تاریخچه وضعیت سفارش نقره",
                "verbose_name_plural": "تاریخچه\u200cهای وضعیت سفارش نقره",
            },
        ),
        migrations.AlterModelOptions(
            name="silverproduct",
            options={
                "verbose_name": "محصول نقره",
                "verbose_name_plural": "محصولات نقره",
            },
        ),
        migrations.AlterModelOptions(
            name="silverproductcategory",
            options={
                "verbose_name": "دسته بندی محصولات نقره",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای محصولات نقره",
            },
        ),
        migrations.RemoveField(
            model_name="silverorder",
            name="admin_note",
        ),
        migrations.RemoveField(
            model_name="silverorder",
            name="description",
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="delivery_type",
            field=models.CharField(
                choices=[("HOME", "ارسال به منزل"), ("IN_PERSON", "تحویل حضوری")],
                default="HOME",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "درخواست سفارش"),
                    ("PREPARING", "در حال آماده\u200cسازی"),
                    ("DELIVERING", "در حال تحویل"),
                    ("DELIVERED", "تحویل داده شد"),
                    ("CANCELLED", "لغو شده"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="total_silver_amount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="total_toman_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="tracking_code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="silverorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="silver_app.silverproduct",
            ),
        ),
        migrations.AlterField(
            model_name="silverorderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="silverorderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="silver_app.silverorder",
            ),
        ),
        migrations.AlterField(
            model_name="silverorderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "درخواست سفارش"),
                    ("PREPARING", "در حال آماده\u200cسازی"),
                    ("DELIVERING", "در حال تحویل"),
                    ("DELIVERED", "تحویل داده شد"),
                    ("CANCELLED", "لغو شده"),
                ],
                max_length=30,
            ),
        ),
    ]
