# Generated by Django 6.0.4 on 2026-07-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("silver_app", "0011_alter_silverorder_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="silverorder",
            options={},
        ),
        migrations.AlterModelOptions(
            name="silverorderitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="silverorderstatushistory",
            options={
                "ordering": ["created_at"],
                "verbose_name": "مرحله سفارش نقره",
                "verbose_name_plural": "مراحل سفارش نقره",
            },
        ),
        migrations.AlterModelOptions(
            name="silverproduct",
            options={},
        ),
        migrations.AlterModelOptions(
            name="silverproductcategory",
            options={},
        ),
        migrations.AddField(
            model_name="silverorder",
            name="admin_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="silverorder",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="delivery_type",
            field=models.CharField(
                choices=[("HOME", "ارسال"), ("IN_PERSON", "حضوری")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "درخواست سفارش"),
                    ("PREPARING", "در حال آماده\u200cسازی"),
                    ("DELIVERING", "در حال تحویل"),
                    ("DELIVERED", "تحویل داده شد"),
                    ("CANCELLED", "لغو شده"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="total_silver_amount",
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="total_toman_amount",
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="silverorder",
            name="tracking_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="silverorderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="silver_app.silverproduct",
            ),
        ),
        migrations.AlterField(
            model_name="silverorderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="silverorderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="silver_app.silverorder",
            ),
        ),
        migrations.AlterField(
            model_name="silverorderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "درخواست سفارش"),
                    ("PREPARING", "در حال آماده\u200cسازی"),
                    ("DELIVERING", "در حال تحویل"),
                    ("DELIVERED", "تحویل داده شد"),
                    ("CANCELLED", "لغو شده"),
                ],
                max_length=20,
            ),
        ),
    ]
