# Generated by Django 6.0.4 on 2026-07-10 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("silver_app", "0012_alter_silverorder_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SilverLimitOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("BUY", "خرید"), ("SELL", "فروش")], max_length=10
                    ),
                ),
                ("target_price", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "amount_toman",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                (
                    "silver_weight",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=20, null=True
                    ),
                ),
                (
                    "estimated_weight",
                    models.DecimalField(decimal_places=3, max_digits=20),
                ),
                (
                    "fee_rate",
                    models.DecimalField(decimal_places=4, default=0.0099, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("EXECUTED", "انجام شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "executed_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="silver_limit_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش با قیمت نقره",
                "verbose_name_plural": "سفارش\u200cهای با قیمت نقره",
                "ordering": ["-created_at"],
            },
        ),
    ]
