# Generated by Django 6.0.4 on 2026-07-25 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("silver_app", "0015_silverinvoice"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="silverinvoice",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "فاکتور نقره",
                "verbose_name_plural": "فاکتورهای نقره",
            },
        ),
        migrations.AddField(
            model_name="silverinvoice",
            name="buyer_province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="استان خریدار"
            ),
        ),
        migrations.AddField(
            model_name="silverinvoice",
            name="seller_province",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="استان فروشنده"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="buyer_address",
            field=models.TextField(blank=True, null=True, verbose_name="آدرس خریدار"),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="buyer_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نام خریدار"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="buyer_national_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="کد ملی خریدار"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="buyer_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="تلفن خریدار"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="توضیحات"),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="fee_amount",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=20, verbose_name="مبلغ کارمزد"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="fee_rate",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="درصد کارمزد"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="invoice_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ فاکتور"),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="invoice_number",
            field=models.CharField(
                editable=False, max_length=50, unique=True, verbose_name="شماره فاکتور"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="invoice_type",
            field=models.CharField(
                choices=[("BUY", "خرید"), ("SELL", "فروش")],
                max_length=10,
                verbose_name="نوع فاکتور",
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="pure_silver_price",
            field=models.DecimalField(
                decimal_places=0, max_digits=20, verbose_name="قیمت خالص نقره"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="seller_address",
            field=models.TextField(blank=True, null=True, verbose_name="آدرس فروشنده"),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="seller_name",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="نام فروشنده"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="seller_national_id",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="کد ملی فروشنده"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="seller_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="تلفن فروشنده"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="silver_price_per_gram",
            field=models.DecimalField(
                decimal_places=0, max_digits=20, verbose_name="قیمت هر گرم نقره"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="silver_weight",
            field=models.DecimalField(
                decimal_places=3, max_digits=20, verbose_name="وزن نقره (گرم)"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "در انتظار"),
                    ("CONFIRMED", "تایید شده"),
                    ("REJECTED", "رد شده"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=0, max_digits=20, verbose_name="مبلغ کل"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="tracking_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="کد رهگیری"
            ),
        ),
        migrations.AlterField(
            model_name="silverinvoice",
            name="transaction",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="silver_invoices",
                to="silver_app.silvertransaction",
                verbose_name="تراکنش",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="silverinvoice",
            table=None,
        ),
    ]
