# Generated by Django 6.0.4 on 2026-07-28 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("silver_app", "0016_alter_silverinvoice_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="silverinvoice",
            name="seller_national_id",
        ),
        migrations.RemoveField(
            model_name="silverinvoice",
            name="seller_phone",
        ),
    ]
