# Generated by Django 6.0.4 on 2026-07-19 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("link", models.URLField(blank=True, null=True, verbose_name="لینک")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "اطلاعیه طلا",
                "verbose_name_plural": "اطلاعیه\u200cهای طلا",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoldBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "image",
                    models.ImageField(upload_to="gold/banners/", verbose_name="تصویر"),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="لینک")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "بنر طلا",
                "verbose_name_plural": "بنرهای طلا",
            },
        ),
        migrations.CreateModel(
            name="SilverAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                ("description", models.TextField(verbose_name="توضیحات")),
                ("link", models.URLField(blank=True, null=True, verbose_name="لینک")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "اطلاعیه نقره",
                "verbose_name_plural": "اطلاعیه\u200cهای نقره",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SilverBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان")),
                (
                    "image",
                    models.ImageField(
                        upload_to="silver/banners/", verbose_name="تصویر"
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="لینک")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "بنر نقره",
                "verbose_name_plural": "بنرهای نقره",
            },
        ),
        migrations.CreateModel(
            name="GoldBalanceAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "gold_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=20),
                ),
                ("admin_note", models.TextField(blank=True, null=True)),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="کد رهگیری"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_gold_balance_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_balance_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "افزایش موجودی طلا",
                "verbose_name_plural": "افزایش موجودی طلا",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="GoldBalanceWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "gold_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=20),
                ),
                ("admin_note", models.TextField(blank=True, null=True)),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="کد رهگیری"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_gold_balance_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_balance_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "برداشت موجودی طلا",
                "verbose_name_plural": "برداشت موجودی طلا",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="GoldPriceOffset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offset_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "set_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SilverBalanceAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "silver_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=20),
                ),
                ("admin_note", models.TextField(blank=True, null=True)),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="کد رهگیری"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_silver_balance_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="silver_balance_adjustments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "افزایش موجودی نقره",
                "verbose_name_plural": "افزایش موجودی نقره",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SilverBalanceWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "silver_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=20),
                ),
                ("admin_note", models.TextField(blank=True, null=True)),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=50, unique=True, verbose_name="کد رهگیری"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_silver_balance_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="silver_balance_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "برداشت موجودی نقره",
                "verbose_name_plural": "برداشت موجودی نقره",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SilverPriceOffset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offset_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "set_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("AUTH", "Authentication"),
                            ("USER", "User"),
                            ("ADMIN", "Admin"),
                            ("GOLD", "Gold"),
                            ("SILVER", "Silver"),
                            ("WALLET", "Wallet"),
                            ("ORDER", "Order"),
                            ("PAYMENT", "Payment"),
                            ("PRICE", "Price"),
                            ("PRODUCT", "Product"),
                            ("GIFT_CARD", "Gift Card"),
                            ("SETTING", "Setting"),
                            ("SECURITY", "Security"),
                            ("SERVER", "Server"),
                            ("SYSTEM", "System"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("ERROR", "Error"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="INFO",
                        max_length=20,
                    ),
                ),
                ("app_name", models.CharField(blank=True, max_length=100, null=True)),
                ("model_name", models.CharField(blank=True, max_length=100, null=True)),
                ("object_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=300, null=True)),
                ("request_data", models.JSONField(blank=True, null=True)),
                ("response_data", models.JSONField(blank=True, null=True)),
                ("response_status", models.PositiveIntegerField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("forwarded_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("browser", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "browser_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("os", models.CharField(blank=True, max_length=100, null=True)),
                ("device", models.CharField(blank=True, max_length=100, null=True)),
                ("device_type", models.CharField(blank=True, max_length=50, null=True)),
                ("old_data", models.JSONField(blank=True, null=True)),
                ("new_data", models.JSONField(blank=True, null=True)),
                ("changed_fields", models.JSONField(blank=True, null=True)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, db_index=True, max_length=150, null=True
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("extra", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="admin_panel_created_0ec78a_idx"
                    ),
                    models.Index(
                        fields=["action_type"], name="admin_panel_action__73d78a_idx"
                    ),
                    models.Index(
                        fields=["action"], name="admin_panel_action_1cea96_idx"
                    ),
                    models.Index(
                        fields=["user"], name="admin_panel_user_id_be0d15_idx"
                    ),
                    models.Index(
                        fields=["admin"], name="admin_panel_admin_i_b8ba29_idx"
                    ),
                    models.Index(
                        fields=["tracking_code"], name="admin_panel_trackin_cc244b_idx"
                    ),
                    models.Index(
                        fields=["response_status"],
                        name="admin_panel_respons_e0a163_idx",
                    ),
                    models.Index(
                        fields=["success"], name="admin_panel_success_e4636e_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GoldAnnouncementRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.goldannouncement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "announcement")},
            },
        ),
        migrations.CreateModel(
            name="SilverAnnouncementRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admin_panel.silverannouncement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "announcement")},
            },
        ),
    ]
