# Generated by Django 6.0.4 on 2026-07-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldbalanceadjustment",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="کد رهگیری",
            ),
        ),
        migrations.AlterField(
            model_name="goldbalancewithdrawal",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="کد رهگیری",
            ),
        ),
        migrations.AlterField(
            model_name="silverbalanceadjustment",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="کد رهگیری",
            ),
        ),
        migrations.AlterField(
            model_name="silverbalancewithdrawal",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="کد رهگیری",
            ),
        ),
    ]
