# Generated by Django 6.0.4 on 2026-06-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_goldbanner_silverbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldbanner',
            name='image',
            field=models.ImageField(upload_to='gold/banners/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='silverbanner',
            name='image',
            field=models.ImageField(upload_to='silver/banners/', verbose_name='تصویر'),
        ),
    ]
