# Generated by Django 6.0.4 on 2026-06-30 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0009_goldannouncement_silverannouncement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adminlog",
            name="app_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="browser",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="browser_version",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="changed_fields",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="device",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="duration_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="endpoint",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="extra",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="forwarded_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="level",
            field=models.CharField(
                choices=[
                    ("INFO", "Info"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("CRITICAL", "Critical"),
                ],
                default="INFO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("GET", "GET"),
                    ("POST", "POST"),
                    ("PUT", "PUT"),
                    ("PATCH", "PATCH"),
                    ("DELETE", "DELETE"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="new_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="old_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="os",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="request_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="response_data",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="response_status",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="session_key",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="success",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="tracking_code",
            field=models.CharField(
                blank=True, db_index=True, max_length=150, null=True
            ),
        ),
        migrations.AddField(
            model_name="adminlog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="action",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("AUTH", "Authentication"),
                    ("USER", "User"),
                    ("ADMIN", "Admin"),
                    ("GOLD", "Gold"),
                    ("SILVER", "Silver"),
                    ("WALLET", "Wallet"),
                    ("ORDER", "Order"),
                    ("PAYMENT", "Payment"),
                    ("PRICE", "Price"),
                    ("PRODUCT", "Product"),
                    ("GIFT_CARD", "Gift Card"),
                    ("SETTING", "Setting"),
                    ("SECURITY", "Security"),
                    ("SERVER", "Server"),
                    ("SYSTEM", "System"),
                    ("OTHER", "Other"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="admin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="model_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="object_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="adminlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminlog",
            index=models.Index(
                fields=["created_at"], name="admin_panel_created_0ec78a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminlog",
            index=models.Index(
                fields=["action_type"], name="admin_panel_action__73d78a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminlog",
            index=models.Index(fields=["action"], name="admin_panel_action_1cea96_idx"),
        ),
        migrations.AddIndex(
            model_name="adminlog",
            index=models.Index(fields=["user"], name="admin_panel_user_id_be0d15_idx"),
        ),
        migrations.AddIndex(
            model_name="adminlog",
            index=models.Index(fields=["admin"], name="admin_panel_admin_i_b8ba29_idx"),
        ),
        migrations.AddIndex(
            model_name="adminlog",
            index=models.Index(
                fields=["tracking_code"], name="admin_panel_trackin_cc244b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminlog",
            index=models.Index(
                fields=["response_status"], name="admin_panel_respons_e0a163_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminlog",
            index=models.Index(
                fields=["success"], name="admin_panel_success_e4636e_idx"
            ),
        ),
    ]
