# Generated by Django 6.0.4 on 2026-07-06 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0013_goldbalanceadjustment_silverbalanceadjustment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldBalanceWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "gold_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=20),
                ),
                ("admin_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_gold_balance_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_balance_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "برداشت موجودی طلا",
                "verbose_name_plural": "برداشت موجودی طلا",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="SilverBalanceWithdrawal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wallet_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "silver_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=20),
                ),
                ("admin_note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_silver_balance_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="silver_balance_withdrawals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "برداشت موجودی نقره",
                "verbose_name_plural": "برداشت موجودی نقره",
                "ordering": ["-id"],
            },
        ),
    ]
