# Generated by Django 6.0.4 on 2026-05-30 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0003_bankcard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=0, max_digits=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[
                            ("HOME", "ارسال به منزل"),
                            ("IN_PERSON", "تحویل حضوری"),
                        ],
                        default="HOME",
                        max_length=20,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "total_weight_with_fees",
                    models.DecimalField(decimal_places=5, default=0, max_digits=20),
                ),
                (
                    "buy_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                (
                    "sell_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                ("inventory_count", models.PositiveIntegerField(default=0)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="AutoSavingPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("DAILY", "روزانه"),
                            ("WEEKLY", "هفتگی"),
                            ("MONTHLY", "ماهانه"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("period_days", models.PositiveIntegerField()),
                ("next_execute_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "فعال"), ("PAUSED", "متوقف")],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saving_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "type",
                    models.CharField(
                        choices=[("DEPOSIT", "واریز"), ("WITHDRAW", "برداشت")],
                        max_length=20,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("ONLINE", "آنلاین"),
                            ("CARD_TO_CARD", "کارت به کارت"),
                            ("BANK", "بانکی"),
                            ("SILVER", "تبدیل به نقره"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("COMPLETED", "تکمیل شده"),
                            ("FAILED", "ناموفق"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "receipt_image",
                    models.ImageField(blank=True, null=True, upload_to="receipts/"),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("admin_note", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.bankcard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GiftCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("weight", models.DecimalField(decimal_places=5, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "ACTIVE"),
                            ("USED", "USED"),
                            ("EXPIRED", "EXPIRED"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "activated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activated_gift_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_gift_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GiftCardOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_per_card",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("total_price", models.DecimalField(decimal_places=0, max_digits=20)),
                ("province", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("plaque", models.CharField(blank=True, max_length=20, null=True)),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("COMPLETED", "تکمیل شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("tracking_code", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoldInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=5, default=0, max_digits=20),
                ),
                (
                    "blocked_balance",
                    models.DecimalField(decimal_places=5, default=0, max_digits=20),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_inventory",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoldTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("BUY", "خرید"), ("SELL", "فروش")], max_length=20
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("COMPLETED", "تکمیل شده"),
                            ("FAILED", "ناموفق"),
                        ],
                        default="COMPLETED",
                        max_length=20,
                    ),
                ),
                ("amount_gr", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "price_per_gram",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                (
                    "fee",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("tracking_code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("plaque", models.CharField(blank=True, max_length=20, null=True)),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("GOLD", "طلا"), ("TOMAN", "کیف پول")], max_length=20
                    ),
                ),
                (
                    "delivery_type",
                    models.CharField(
                        choices=[("HOME", "ارسال"), ("IN_PERSON", "حضوری")],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("PROCESSING", "در حال پردازش"),
                            ("SHIPPED", "ارسال شده"),
                            ("COMPLETED", "تکمیل شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "total_gold_amount",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                (
                    "total_toman_amount",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                ("tracking_code", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_price", models.DecimalField(decimal_places=5, max_digits=20)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[("ABOVE", "بالاتر"), ("BELOW", "پایین\u200cتر")],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("price_at_time", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "weight_at_time",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="gold_app.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gold_app.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="gold_app.productcategory",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseCredit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "used_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "فعال"),
                            ("USED", "استفاده شده"),
                            ("EXPIRED", "منقضی شده"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("expire_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReferralEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("transaction_date", models.DateTimeField(auto_now_add=True)),
                (
                    "referred_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="earned_from_me",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "referrer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referral_earnings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("address", models.TextField()),
                ("postal_code", models.CharField(blank=True, max_length=20, null=True)),
                ("plaque", models.CharField(blank=True, max_length=20, null=True)),
                ("unit", models.CharField(blank=True, max_length=20, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                (
                    "blocked_balance",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
