# Generated by Django 6.0.8 on 2026-09-05 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش طلا', 'verbose_name_plural': 'تراکنش\u200cهای طلا'},
        ),
        migrations.AddField(
            model_name='goldtransaction',
            name='request_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه درخواست'),
        ),
        migrations.AddField(
            model_name='goldtransaction',
            name='talasea_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه سفارش در طلاسی'),
        ),
        migrations.AddField(
            model_name='goldtransaction',
            name='talasea_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='پاسخ کامل طلاسی'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='amount_gr',
            field=models.DecimalField(decimal_places=3, max_digits=20, verbose_name='مقدار طلا (گرم)'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='commission_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مبلغ کارمزد'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد کارمزد'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مبلغ کارمزد'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='marketer_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد سود معرف'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='price_per_gram',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='قیمت هر گرم (تومان)'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='profit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20, verbose_name='مبلغ سود معرف'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ کل (تومان)'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='tracking_code',
            field=models.CharField(max_length=100, unique=True, verbose_name='کد رهگیری'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='goldtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
