# Generated by Django 6.0.4 on 2026-05-30 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("BUY", "خرید"), ("SELL", "فروش")], max_length=10
                    ),
                ),
                ("target_price", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "amount_toman",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                (
                    "gold_weight",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=20, null=True
                    ),
                ),
                (
                    "estimated_weight",
                    models.DecimalField(decimal_places=5, max_digits=20),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("EXECUTED", "انجام شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "executed_price",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=20, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
