# Generated by Django 6.0.4 on 2026-04-25 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankcard'),
        ('gold_app', '0002_wallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminBankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('account_number', models.CharField(max_length=20, verbose_name='شماره حساب')),
                ('shaba_number', models.CharField(max_length=26, verbose_name='شماره شبا')),
                ('owner_name', models.CharField(max_length=100, verbose_name='بنام')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'اطلاعات حساب مدیریت',
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=20)),
                ('type', models.CharField(choices=[('DEPOSIT', 'واریز'), ('WITHDRAW', 'برداشت')], max_length=10)),
                ('method', models.CharField(choices=[('GATEWAY', 'درگاه بانکی'), ('CARD', 'کارت به کارت')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('SUCCESS', 'موفق'), ('REJECTED', 'رد شده')], default='PENDING', max_length=10)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankcard')),
            ],
        ),
    ]
