# Generated by Django 6.0.8 on 2026-09-17 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0002_alter_goldtransaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='apartment_number',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='balance_released',
            field=models.BooleanField(
                default=False,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='building_number',
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='receiver_first_name',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='receiver_last_name',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='receiver_lat',
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=15,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='receiver_long',
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=15,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='reserved_gold_amount',
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=20,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='reserved_toman_amount',
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=20,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_address_id',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_delivery_irt',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=20,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_fee_irt',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=20,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_gold_price',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=20,
                null=True,
                verbose_name='قیمت طلا در زمان سفارش',
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_insurance_irt',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=20,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_pure_gold',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=20,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_request_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                verbose_name='شناسه درخواست طلاسی',
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_request_ids',
            field=models.JSONField(
                blank=True,
                default=list,
                verbose_name='شناسه‌های درخواست طلاسی',
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_response',
            field=models.JSONField(
                blank=True,
                default=dict,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_shipment_cost_gold',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=20,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_shipment_cost_irt',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=20,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_status',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=100,
                null=True,
                verbose_name='وضعیت طلاسی',
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_time_id',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_total_gold',
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=20,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='order',
            name='talasea_total_irt',
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=20,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
            ),
            preserve_default=False,
        ),

        migrations.AddField(
            model_name='orderitem',
            name='talasea_commodity_id',
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
            ),
        ),

        migrations.AddField(
            model_name='orderitem',
            name='talasea_item_data',
            field=models.JSONField(
                blank=True,
                default=dict,
            ),
        ),

        migrations.AddField(
            model_name='product',
            name='talasea_commodity_id',
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name='شناسه کالا در طلاسی',
            ),
        ),

        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(
                blank=True,
                default='',
            ),
        ),

        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(
                blank=True,
                default='',
                max_length=100,
            ),
        ),

        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(
                blank=True,
                default='',
                max_length=100,
            ),
        ),

        migrations.AlterField(
            model_name='order',
            name='total_gold_amount',
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=20,
            ),
        ),

        migrations.AlterField(
            model_name='order',
            name='total_toman_amount',
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=20,
            ),
        ),

        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]