# Generated by Django 6.0.8 on 2026-09-18 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0003_order_apartment_number_order_balance_released_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='apartment_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='balance_released',
        ),
        migrations.RemoveField(
            model_name='order',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_lat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiver_long',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reserved_gold_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='reserved_toman_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_address_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_delivery_irt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_fee_irt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_gold_price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_insurance_irt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_pure_gold',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_request_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_request_ids',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_response',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_shipment_cost_gold',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_shipment_cost_irt',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_time_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_total_gold',
        ),
        migrations.RemoveField(
            model_name='order',
            name='talasea_total_irt',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='talasea_commodity_id',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='talasea_item_data',
        ),
        migrations.RemoveField(
            model_name='product',
            name='talasea_commodity_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_gold_amount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_toman_amount',
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
