# Generated by Django 6.0.4 on 2026-05-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0003_goldorder_fee_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReferralEarning',
        ),
    ]
