# Generated by Django 6.0.4 on 2026-04-25 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankcard'),
        ('gold_app', '0003_adminbankinfo_financialtransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminbankinfo',
            options={'verbose_name': 'اطلاعات حساب مدیریت', 'verbose_name_plural': 'اطلاعات حساب مدیریت'},
        ),
        migrations.AlterModelOptions(
            name='financialtransaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'تراکنش مالی', 'verbose_name_plural': 'تراکنش\u200cهای مالی'},
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات مدیریت'),
        ),
        migrations.AddField(
            model_name='financialtransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
        migrations.AlterField(
            model_name='adminbankinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='مبلغ (تومان)'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='method',
            field=models.CharField(choices=[('GATEWAY', 'درگاه بانکی'), ('CARD', 'کارت به کارت')], max_length=10, verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='تصویر رسید'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('SUCCESS', 'موفق'), ('REJECTED', 'رد شده')], default='PENDING', max_length=10, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'واریز'), ('WITHDRAW', 'برداشت')], max_length=10, verbose_name='نوع تراکنش'),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='user_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.bankcard', verbose_name='کارت مقصد کاربر'),
        ),
    ]
