# Generated by Django 6.0.8 on 2026-09-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0004_remove_order_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AddField(
            model_name='order',
            name='national_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='order',
            name='talasea_city_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه شهر طلاسی'),
        ),
        migrations.AddField(
            model_name='order',
            name='talasea_delivery_type',
            field=models.CharField(blank=True, choices=[('PHYSICAL_DELIVERY', 'ارسال با پست'), ('DIGIEXPRESS_DELIVERY', 'ارسال با دیجی\u200cاکسپرس')], max_length=30, null=True, verbose_name='نوع تحویل طلاسی'),
        ),
        migrations.AddField(
            model_name='order',
            name='talasea_request_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شناسه درخواست طلاسی'),
        ),
        migrations.AddField(
            model_name='order',
            name='talasea_response',
            field=models.JSONField(blank=True, default=dict, verbose_name='پاسخ کامل طلاسی'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن کاربر'),
        ),
        migrations.AddField(
            model_name='product',
            name='talasea_category',
            field=models.CharField(blank=True, help_text='مثلاً gold_BAR', max_length=100, null=True, verbose_name='دسته\u200cبندی طلاسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='talasea_commodity_id',
            field=models.CharField(blank=True, help_text='commodityId دریافتی از سرویس /partners/commodity طلاسی', max_length=100, null=True, verbose_name='شناسه کالا در طلاسی'),
        ),
        migrations.AddField(
            model_name='product',
            name='talasea_last_sync',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین همگام\u200cسازی با طلاسی'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('HOME', 'ارسال'), ('IN_PERSON', 'حضوری')], default='HOME', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
