# Generated by Django 6.0.4 on 2026-05-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0004_remove_autosavingplan_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricealert',
            name='target_price',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
    ]
