# Generated by Django 6.0.8 on 2026-09-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0005_order_latitude_order_longitude_order_national_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='talasea_image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL تصویر طلاسی'),
        ),
    ]
