# Generated by Django 6.0.8 on 2026-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0006_product_talasea_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='talasea_irt_price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True, verbose_name='قیمت لحظه\u200cای طلاسی (تومان)'),
        ),
        migrations.AddField(
            model_name='product',
            name='talasea_last_price_update',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخرین بروزرسانی قیمت طلاسی'),
        ),
    ]
