# Generated by Django 6.0.4 on 2026-06-05 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0007_goldbankinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profit_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
