# Generated by Django 6.0.4 on 2026-07-01 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0010_alter_giftcard_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldinventory',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='goldinventory',
            name='blocked_balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
