# Generated by Django 6.0.4 on 2026-07-02 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0012_order_admin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='last_triggered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='last_triggered_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='max_notifications',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='sent_notifications',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'فعال'), ('PAUSED', 'متوقف'), ('FINISHED', 'اتمام')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='pricealert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='PriceAlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=20)),
                ('sms_cost', models.DecimalField(decimal_places=0, default=900, max_digits=10)),
                ('sms_status', models.CharField(choices=[('SUCCESS', 'موفق'), ('FAILED', 'ناموفق'), ('INSUFFICIENT_BALANCE', 'عدم موجودی')], max_length=30)),
                ('sms_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gold_app.pricealert')),
            ],
        ),
    ]
