# Generated by Django 6.0.4 on 2026-07-02 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0013_pricealert_last_triggered_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricealert',
            name='triggered',
            field=models.BooleanField(default=False),
        ),
    ]
