# Generated by Django 6.0.4 on 2026-07-03 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0015_orderstatushistory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrderStatusHistory",
        ),
    ]
