# Generated by Django 6.0.4 on 2026-07-03 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0016_delete_orderstatushistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "درخواست سفارش"),
                    ("PREPARING", "در حال آماده\u200cسازی"),
                    ("DELIVERING", "در حال تحویل"),
                    ("DELIVERED", "تحویل داده شد"),
                    ("CANCELLED", "لغو شده"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "درخواست سفارش"),
                            ("PREPARING", "در حال آماده\u200cسازی"),
                            ("DELIVERING", "در حال تحویل"),
                            ("DELIVERED", "تحویل داده شد"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="gold_app.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرحله سفارش",
                "verbose_name_plural": "مراحل سفارش",
                "ordering": ["created_at"],
            },
        ),
    ]
