# Generated by Django 6.0.4 on 2026-07-04 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0020_remove_goldinventory_balance_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "سفارش طلا", "verbose_name_plural": "سفارشات طلا"},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={
                "verbose_name": "آیتم سفارش طلا",
                "verbose_name_plural": "آیتم\u200cهای سفارش طلا",
            },
        ),
        migrations.AlterModelOptions(
            name="orderstatushistory",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "تاریخچه وضعیت سفارش طلا",
                "verbose_name_plural": "تاریخچه\u200cهای وضعیت سفارش طلا",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "محصول طلا", "verbose_name_plural": "محصولات طلا"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "دسته بندی محصولات طلا",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای محصولات طلا",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="admin_note",
        ),
        migrations.RemoveField(
            model_name="order",
            name="description",
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("HOME", "ارسال به منزل"), ("IN_PERSON", "تحویل حضوری")],
                default="HOME",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "درخواست سفارش"),
                    ("PREPARING", "در حال آماده\u200cسازی"),
                    ("DELIVERING", "در حال تحویل"),
                    ("DELIVERED", "تحویل داده شد"),
                    ("CANCELLED", "لغو شده"),
                ],
                default="REQUESTED",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_gold_amount",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_toman_amount",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="gold_app.product"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="gold_app.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "درخواست سفارش"),
                    ("PREPARING", "در حال آماده\u200cسازی"),
                    ("DELIVERING", "در حال تحویل"),
                    ("DELIVERED", "تحویل داده شد"),
                    ("CANCELLED", "لغو شده"),
                ],
                max_length=30,
            ),
        ),
    ]
