# Generated by Django 6.0.4 on 2026-07-04 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0021_alter_order_options_alter_orderitem_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orderitem",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orderstatushistory",
            options={
                "ordering": ["created_at"],
                "verbose_name": "مرحله سفارش طلا",
                "verbose_name_plural": "مراحل سفارش طلا",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={},
        ),
        migrations.AddField(
            model_name="order",
            name="admin_note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_type",
            field=models.CharField(
                choices=[("HOME", "ارسال"), ("IN_PERSON", "حضوری")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "درخواست سفارش"),
                    ("PREPARING", "در حال آماده\u200cسازی"),
                    ("DELIVERING", "در حال تحویل"),
                    ("DELIVERED", "تحویل داده شد"),
                    ("CANCELLED", "لغو شده"),
                ],
                default="REQUESTED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_gold_amount",
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_toman_amount",
            field=models.DecimalField(decimal_places=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gold_app.product"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="status_history",
                to="gold_app.order",
            ),
        ),
        migrations.AlterField(
            model_name="orderstatushistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "درخواست سفارش"),
                    ("PREPARING", "در حال آماده\u200cسازی"),
                    ("DELIVERING", "در حال تحویل"),
                    ("DELIVERED", "تحویل داده شد"),
                    ("CANCELLED", "لغو شده"),
                ],
                max_length=20,
            ),
        ),
    ]
