# Generated by Django 6.0.4 on 2026-07-10 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0023_alter_goldorder_options_goldorder_description_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldShortOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_type",
                    models.CharField(
                        choices=[("MARKET", "قیمت بازار"), ("LIMIT", "قیمت هدف")],
                        max_length=10,
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=3, max_digits=20)),
                (
                    "leverage",
                    models.PositiveSmallIntegerField(default=1, verbose_name="ضریب"),
                ),
                (
                    "entry_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=20, verbose_name="قیمت ورود"
                    ),
                ),
                (
                    "target_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=20,
                        null=True,
                        verbose_name="قیمت هدف",
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=20,
                        null=True,
                        verbose_name="حد سود",
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=20,
                        null=True,
                        verbose_name="حد ضرر",
                    ),
                ),
                (
                    "close_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=20,
                        null=True,
                        verbose_name="قیمت بسته شدن",
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="سود/ضرر",
                    ),
                ),
                (
                    "initial_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="کارمزد اولیه",
                    ),
                ),
                (
                    "daily_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="کارمزد روزانه",
                    ),
                ),
                (
                    "total_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="کل کارمزد",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("ACTIVE", "فعال"),
                            ("CLOSED", "بسته شده"),
                            ("LIQUIDATED", "لیکوئید شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_short_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "فروش تعهدی طلا",
                "verbose_name_plural": "فروش\u200cهای تعهدی طلا",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GoldShortOrderHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("ACTIVE", "فعال"),
                            ("CLOSED", "بسته شده"),
                            ("LIQUIDATED", "لیکوئید شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=0, max_digits=20)),
                (
                    "profit_loss",
                    models.DecimalField(decimal_places=0, default=0, max_digits=20),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="gold_app.goldshortorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
