# Generated by Django 6.0.4 on 2026-07-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0024_goldshortorder_goldshortorderhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "در انتظار"),
                    ("COMPLETED", "انجام شده"),
                    ("FAILED", "لغو شده"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
