# Generated by Django 6.0.4 on 2026-07-21 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0025_alter_goldorder_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldGuaranteePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام طرح")),
                (
                    "duration_days",
                    models.PositiveIntegerField(verbose_name="مدت تعهد (روز)"),
                ),
                (
                    "service_fee_percent",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="کارمزد سرویس (%)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "طرح تضمین طلا",
                "verbose_name_plural": "طرح\u200cهای تضمین طلا",
                "ordering": ["duration_days"],
            },
        ),
        migrations.CreateModel(
            name="GoldGuarantee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_weight",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=20,
                        verbose_name="مقدار طلای تضمین شده",
                    ),
                ),
                (
                    "guaranteed_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=20, verbose_name="قیمت تضمین شده"
                    ),
                ),
                (
                    "service_fee",
                    models.DecimalField(
                        decimal_places=0, max_digits=20, verbose_name="کارمزد سرویس"
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ شروع"),
                ),
                ("end_date", models.DateTimeField(verbose_name="تاریخ انقضا")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "فعال"),
                            ("EXPIRED", "منقضی شده"),
                            ("CANCELLED", "لغو شده"),
                            ("EXECUTED", "اجرا شده"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ لغو"
                    ),
                ),
                (
                    "executed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ اجرا"
                    ),
                ),
                (
                    "executed_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=20,
                        null=True,
                        verbose_name="قیمت اجرا",
                    ),
                ),
                (
                    "profit_loss",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="سود/ضرر",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guarantee",
                        to="gold_app.goldtransaction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_guarantees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="guarantees",
                        to="gold_app.goldguaranteeplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "تضمین طلا",
                "verbose_name_plural": "تضمین\u200cهای طلا",
                "ordering": ["-created_at"],
            },
        ),
    ]
