# Generated by Django 6.0.4 on 2026-07-21 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0026_goldguaranteeplan_goldguarantee"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoldInvestmentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام طرح")),
                (
                    "duration_months",
                    models.PositiveIntegerField(verbose_name="مدت (ماه)"),
                ),
                (
                    "monthly_profit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="سود ماهانه (%)",
                    ),
                ),
                (
                    "total_profit_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="سود کل (%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "طرح سرمایه\u200cگذاری طلا",
                "verbose_name_plural": "طرح\u200cهای سرمایه\u200cگذاری طلا",
                "ordering": ["duration_months"],
            },
        ),
        migrations.CreateModel(
            name="GoldInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_weight",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=20,
                        verbose_name="مقدار طلای سرمایه\u200cگذاری شده",
                    ),
                ),
                (
                    "investment_price",
                    models.DecimalField(
                        decimal_places=0,
                        max_digits=20,
                        verbose_name="قیمت سرمایه\u200cگذاری",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ شروع"),
                ),
                ("end_date", models.DateTimeField(verbose_name="تاریخ پایان")),
                (
                    "expected_profit",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=20,
                        verbose_name="سود کل مورد انتظار",
                    ),
                ),
                (
                    "paid_profit",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=20,
                        verbose_name="سود پرداخت شده",
                    ),
                ),
                (
                    "paid_profit_toman",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=20,
                        verbose_name="سود پرداخت شده (تومان)",
                    ),
                ),
                (
                    "cancellation_profit",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        max_digits=20,
                        verbose_name="سود انصراف",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "فعال"),
                            ("COMPLETED", "تکمیل شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ لغو"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تکمیل"
                    ),
                ),
                (
                    "last_profit_paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین پرداخت سود"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gold_investments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="investments",
                        to="gold_app.goldinvestmentplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "سرمایه\u200cگذاری طلا",
                "verbose_name_plural": "سرمایه\u200cگذاری\u200cهای طلا",
                "ordering": ["-created_at"],
            },
        ),
    ]
