# Generated by Django 6.0.4 on 2026-07-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0027_goldinvestmentplan_goldinvestment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                (
                    "invoice_type",
                    models.CharField(
                        choices=[("BUY", "فاکتور خرید"), ("SELL", "فاکتور فروش")],
                        max_length=10,
                    ),
                ),
                ("invoice_date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار تایید"),
                            ("CONFIRMED", "تایید شده"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("buyer_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "buyer_national_id",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("buyer_phone", models.CharField(blank=True, max_length=20, null=True)),
                ("buyer_address", models.TextField(blank=True, null=True)),
                (
                    "seller_name",
                    models.CharField(default="فروشگاه دارینه", max_length=200),
                ),
                (
                    "seller_national_id",
                    models.CharField(default="0371439477", max_length=20),
                ),
                (
                    "seller_phone",
                    models.CharField(default="09191608771", max_length=20),
                ),
                (
                    "seller_address",
                    models.TextField(default="قم، پاساژ شهر طلا، پلاک ۲۱"),
                ),
                ("gold_weight", models.DecimalField(decimal_places=3, max_digits=20)),
                ("gold_carat", models.IntegerField(default=18)),
                (
                    "gold_price_per_gram",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                (
                    "pure_gold_price",
                    models.DecimalField(decimal_places=0, max_digits=20),
                ),
                ("fee_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fee_amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("total_amount", models.DecimalField(decimal_places=0, max_digits=20)),
                ("tracking_code", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="gold_app.goldtransaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
