# Generated by Django 6.0.4 on 2026-07-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0029_alter_invoice_options_invoice_buyer_province_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldguarantee",
            name="platform_profit",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=20, verbose_name="سود پلتفرم"
            ),
        ),
        migrations.AddField(
            model_name="goldguarantee",
            name="user_payout",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=20,
                verbose_name="مبلغ پرداختی به کاربر",
            ),
        ),
    ]
