# Generated by Django 6.0.4 on 2026-07-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0030_goldguarantee_platform_profit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldguarantee",
            name="profit_loss",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=20,
                verbose_name="سود کل (مبلغ پرداختی به کاربر)",
            ),
        ),
    ]
