# Generated by Django 6.0.4 on 2026-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0031_alter_goldguarantee_profit_loss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldguarantee",
            name="executed_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=20,
                null=True,
                verbose_name="قیمت اجرا (قیمت اتمام)",
            ),
        ),
        migrations.AlterField(
            model_name="goldguarantee",
            name="guaranteed_price",
            field=models.DecimalField(
                decimal_places=0,
                max_digits=20,
                verbose_name="قیمت تضمین شده (قیمت شروع)",
            ),
        ),
    ]
