# Generated by Django 6.0.4 on 2026-07-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0032_alter_goldguarantee_executed_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="goldinvestmentplan",
            options={
                "ordering": ["duration_days"],
                "verbose_name": "طرح سرمایه\u200cگذاری طلا",
                "verbose_name_plural": "طرح\u200cهای سرمایه\u200cگذاری طلا",
            },
        ),
        migrations.RemoveField(
            model_name="goldinvestmentplan",
            name="duration_months",
        ),
        migrations.RemoveField(
            model_name="goldinvestmentplan",
            name="monthly_profit_percent",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="seller_national_id",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="seller_phone",
        ),
        migrations.AddField(
            model_name="goldinvestmentplan",
            name="daily_profit_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="سود به ازای هر روز (مثلاً 0.005 = 0.5% در روز)",
                max_digits=10,
                verbose_name="سود روزانه (%)",
            ),
        ),
        migrations.AddField(
            model_name="goldinvestmentplan",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=1,
                help_text="تعداد روزهای سرمایه\u200cگذاری (مثلاً 1، 30، 90، 180، 365، 1000)",
                verbose_name="مدت سرمایه\u200cگذاری (روز)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="goldinvestmentplan",
            name="total_profit_percent",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="سود کل = سود روزانه × تعداد روز",
                max_digits=10,
                verbose_name="سود کل (%)",
            ),
        ),
    ]
