# Generated by Django 6.0.4 on 2026-07-29 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0033_alter_goldinvestmentplan_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="goldguarantee",
            name="tracking_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=50,
                null=True,
                unique=True,
                verbose_name="کد رهگیری",
            ),
        ),
    ]
