# Generated by Django 6.0.4 on 2026-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gold_app", "0034_goldguarantee_tracking_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goldguarantee",
            name="profit_loss",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=20,
                verbose_name="سود کل (همیشه ۰)",
            ),
        ),
        migrations.AlterField(
            model_name="goldguarantee",
            name="user_payout",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=20,
                verbose_name="مبلغ پرداختی به کاربر (همیشه ۰)",
            ),
        ),
    ]
