# Generated by Django 6.0.4 on 2026-06-04 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_feesetting_gold_referral_percent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gold_buy_fee",
                    models.DecimalField(decimal_places=4, default=0.0099, max_digits=5),
                ),
                (
                    "gold_sell_fee",
                    models.DecimalField(decimal_places=4, default=0.0099, max_digits=5),
                ),
                (
                    "silver_buy_fee",
                    models.DecimalField(decimal_places=4, default=0.01, max_digits=5),
                ),
                (
                    "silver_sell_fee",
                    models.DecimalField(decimal_places=4, default=0.01, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
