# Generated by Django 6.0.4 on 2026-07-01 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_bankcard_shaba_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankcard",
            name="shaba_number",
            field=models.CharField(
                blank=True, max_length=26, null=True, verbose_name="شماره شبا"
            ),
        ),
    ]
