# Generated by Django 6.0.4 on 2026-07-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_bankcard_shaba_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='shaba_number',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='شماره شبا'),
        ),
    ]
