# Generated by Django 6.0.4 on 2026-07-03 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_bankcard_shaba_number"),
    ]

    operations = [
        migrations.RenameField(
            model_name="referralearning",
            old_name="amount",
            new_name="commission_amount",
        ),
        migrations.RemoveField(
            model_name="feesetting",
            name="gold_fee",
        ),
        migrations.RemoveField(
            model_name="feesetting",
            name="silver_fee",
        ),
        migrations.RemoveField(
            model_name="userfee",
            name="created_at",
        ),
        migrations.AddField(
            model_name="feesetting",
            name="gold_buy_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="درصد کارمزد خرید طلا",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="feesetting",
            name="gold_sell_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="درصد کارمزد فروش طلا",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="feesetting",
            name="silver_buy_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="درصد کارمزد خرید نقره",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="feesetting",
            name="silver_sell_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="درصد کارمزد فروش نقره",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="referralearning",
            name="commission_percent",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referralearning",
            name="marketer_percent",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referralearning",
            name="profit",
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="referralearning",
            name="transaction_amount",
            field=models.DecimalField(decimal_places=0, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feesetting",
            name="gold_referral_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="درصد سود معرف از کارمزد طلا",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="feesetting",
            name="silver_referral_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=20.0,
                help_text="درصد سود معرف از کارمزد نقره",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="referralearning",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_referral_earnings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userfee",
            name="gold_buy_fee",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="userfee",
            name="gold_sell_fee",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="userfee",
            name="silver_buy_fee",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="userfee",
            name="silver_sell_fee",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5),
        ),
    ]
