# Generated by Django 6.0.4 on 2026-07-08 07:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_rename_amount_referralearning_commission_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feesetting",
            name="gold_buy_fee",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.01"),
                help_text="نرخ کارمزد خرید طلا (مثال: 0.01 = 1% ، 0.03 = 3%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="feesetting",
            name="gold_referral_percent",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name="feesetting",
            name="gold_sell_fee",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.01"),
                help_text="نرخ کارمزد فروش طلا",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="feesetting",
            name="silver_buy_fee",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.01"),
                help_text="نرخ کارمزد خرید نقره",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="feesetting",
            name="silver_referral_percent",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AlterField(
            model_name="feesetting",
            name="silver_sell_fee",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.01"),
                help_text="نرخ کارمزد فروش نقره",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="userfee",
            name="gold_buy_fee",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.01"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="userfee",
            name="gold_sell_fee",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.01"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="userfee",
            name="silver_buy_fee",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.01"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="userfee",
            name="silver_sell_fee",
            field=models.DecimalField(
                decimal_places=4, default=Decimal("0.01"), max_digits=5
            ),
        ),
    ]
