# Generated by Django 6.0.4 on 2026-07-09 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_feesetting_gold_buy_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReferralSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "commission_percent",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="referral_code",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="کد معرف اختصاصی",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="referrals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="معرف",
            ),
        ),
    ]
