# Generated by Django 6.0.4 on 2026-07-10 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_referralsetting_alter_user_referral_code_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referralsetting",
            options={
                "verbose_name": "تنظیمات رفرال",
                "verbose_name_plural": "تنظیمات رفرال",
            },
        ),
        migrations.AlterField(
            model_name="referralsetting",
            name="commission_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=20,
                max_digits=5,
                verbose_name="درصد سود رفرال",
            ),
        ),
    ]
