# Generated by Django 6.0.4 on 2026-07-20 10:02

import accounts.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_ticketcategory_ticket_ticketmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="auto_resolved",
            field=models.BooleanField(default=False, verbose_name="حل شده خودکار"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="last_activity_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین فعالیت"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="tracking_code",
            field=models.CharField(
                default=1,
                editable=False,
                max_length=20,
                unique=True,
                verbose_name="کد رهگیری",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounts.models.ticket_attachment_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "svg",
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "zip",
                            "rar",
                            "7z",
                            "txt",
                            "csv",
                            "json",
                            "xml",
                        ]
                    )
                ],
                verbose_name="فایل ضمیمه",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "باز"),
                    ("in_progress", "در حال بررسی"),
                    ("pending", "در انتظار پاسخ کاربر"),
                    ("answered", "پاسخ داده شده"),
                    ("resolved", "حل شده"),
                    ("closed", "بسته شده"),
                ],
                default="open",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="ticketmessage",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounts.models.ticket_message_attachment_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "bmp",
                            "svg",
                            "pdf",
                            "doc",
                            "docx",
                            "xls",
                            "xlsx",
                            "ppt",
                            "pptx",
                            "zip",
                            "rar",
                            "7z",
                            "txt",
                            "csv",
                            "json",
                            "xml",
                        ]
                    )
                ],
                verbose_name="فایل ضمیمه",
            ),
        ),
    ]
