# Generated by Django 6.0.4 on 2026-05-22 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_gift_cards', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcard',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('USED', 'USED'), ('EXPIRED', 'EXPIRED')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='activated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activated_gift_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='giftcard',
            name='weight',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
