# Generated by Django 6.0.4 on 2026-05-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0002_giftcard_created_by_giftcard_status_giftcard_used_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autosavingplan',
            name='frequency',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='autosavingplan',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
