# Generated by Django 6.0.4 on 2026-05-22 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_app', '0003_autosavingplan_frequency_autosavingplan_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autosavingplan',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='autosavingplan',
            name='title',
        ),
        migrations.AlterField(
            model_name='autosavingplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
