# Generated by Django 6.0.4 on 2026-04-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='silvertransaction',
            name='type',
            field=models.CharField(choices=[('BUY', 'خرید'), ('SELL', 'فروش'), ('CONVERT', 'تبدیل از ریال')], default='BUY', max_length=10),
        ),
    ]
