# Generated by Django 6.0.4 on 2026-05-10 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silver_app', '0004_alter_bankcard_user_alter_silvertransaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SilverProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('weight_gr', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='وزن خالص (گرم)')),
                ('total_weight_with_packaging', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='وزن با صرب و بسته\u200cبندی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalDeliveryOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_at_time_of_order', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_price_toman', models.DecimalField(decimal_places=0, max_digits=20)),
                ('payment_method', models.CharField(choices=[('SILVER', 'پرداخت با نقره'), ('TOMAN', 'پرداخت با تومان')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار بررسی'), ('PREPARING', 'در حال آماده\u200cسازی'), ('SHIPPED', 'ارسال شده'), ('DELIVERED', 'تحویل شده')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='silver_app.silverproduct')),
            ],
        ),
    ]
